name: Greet on Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet contributor
        run: echo "Thanks for your pull request to HeroHub! We appreciate your contribution."